### PR TITLE
New filters "ARRAY_CONTAINS" and "ARRAY_NOT_CONTAINS"

### PR DESCRIPTION
**Pull request by yulioaj290**
New filters **ARRAY_CONTAINS** and **ARRAY_NOT_CONTAINS** to make a contain filtering over _**array**_ fields. 
This new filters have been tested with a field of type **array**. 

For example: 
```
/**
 * @ORM\Entity()
 * @ORM\Table(name="student")
 */
class Student
{
    /**
     * @var array
     * @ORM\Column(type="array", name="phones")
     */
    private $phones;
    // ...
}
```

Example of request:
```
/student?filter=[
    {
        "type":"ac",
        "path":"phones",
        "value":"1-800-5555"
    },
    {
        "type":"anc",
        "path":"phones",
        "value":"0-000-0000"
    },
]
```

### CODE REVIEW

**Comment by trivago-makbarof** [comment]
Hey man,
Sorry for answering so late
Here are some points that I see in this PR
1) In this library it's practically impossible to do filtering of values in php side unless you bring all the values which in some cases can be really expensive and hard to maintain.
2) The reason I said the point 1 is because if you filter out data on php you get invalid result
Imagine the following case

id | products
------------ | -------------
1 | [apple iphone, apple ipad]
2 | [apple]

I do a query with limit 1 where array contain apple
The result of the api should be the row with id 2 but in the current implementation I get no result back

One way to fix it is to the query: field LIKE "$word,%" OR field LIKE "%,$word" OR field LIKE "%,$word,%"
This makes sure the actual word exists in the array
But again this implementation has the issue of case sensitivity! Since I can search for apple but the word I have in the database is APPLE which is returns by the query

I really appreciate your effort for this PR but I have a feeling this feature if is not well thought can cause more problems than solving.

So If you are ok with it I'm going to close this one until we can come up with a solution that can guarantee a consistent and correct response

**Comment by moein** [comment]
By the way one small recommendation for future
If you have

```php
foreach ($a as $b) {
  if ($cond) {
    ...
  }
  // Nothing here
}
```

It's a lot cleaner if you just do

```php
foreach ($a as $b) {
  if (!$cond) {
    continue;
  }
  ...
}
```

Specially this helps when looking at the diff in the PR so there are less noises in the diff.

**Comment by trivago-makbarof** [comment]
By the way one small recommendation for future
If you have

```php
foreach ($a as $b) {
  if ($cond) {
    ...
  }
  // Nothing here
}
```

It's a lot cleaner if you just do

```php
foreach ($a as $b) {
  if (!$cond) {
    continue;
  }
  ...
}
```

Specially this helps when looking at the diff in the PR so there are less noises in the diff.

**Comment by yulioaj290** [comment]
Hi Moein.

Thanks for the remconedations, I tried to rollback all code that have been auto arrange (by the IDE) and to clean the final PR, but it's seems that I forgot the **if** condition, and surely it affected the review of the PR, sorry for that!

Well, I just tested (again) the code of the PR now and, the search is **case sensitive**. _Did you mean that you want to do this feature **case insensitive**?_

I'm agree with you, this feature need a well thought.

I have done a search on the entire library code about a limit option, and I suppose you have used an external way to limit the rows of the response, because I have no found this kind of option.

Related to this topic, if you create a new filter of type limit, to control the quantity of rows of the response using PHP code, the idea of this PR is still useful, only needs some changes. I mean to do the limit at the end of all filters, just before return the rows filtered from DB.

Maybe this new ideas will bring more problems, it need to analyze the whole environment of the library. As you have a lot of knowledge about the implementation, Tell me if we can try to refactor the PR with the new ideas to make it functional. I just want to contribute :).

P.S.: Dont worry about answer late, we have 6 hours of difference. A greeting from Cuba.

**Comment by trivago-makbarof** [comment]
@yulioaj290 You're current implementation IS case sensitive and that's good
I mentioned case sensitivity in case of just using LIKE in mysql
Jade supports pagination and it's applied here:
https://github.com/trivago/jade/blob/52030919cd6428861d7d88e1ce9005a95f8da1ed/Trivago/Jade/Infrastructure/Repository/DoctrineResourceRepository.php#L220

**Comment by yulioaj290** [comment]
@trivago-makbarof I can see now. Well, most of filtering features are written at DB level, that means the new type of contain filtering for arrays should be write at DB level. The main obstacle is that Doctrine handle the arrays of Symfony2+ as a string field, and at DB level to handle that data as array would be difficult. 

I think that to use a LIKE clause is not the best option, not only because the reasons you said above, but also that a string field can accept many kind of values inside the array structure, and to provoke confusion to the LIKE clause.

**Pull request closed without merging**
